/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    employees: Employee;
    branches: Branch;
    applications: Application;
    'wellness-leaves': WellnessLeaf;
    'itr-submissions': ItrSubmission;
    'sworn-declarations': SwornDeclaration;
    'pds-submissions': PdsSubmission;
    'ipcr-ratings': IpcrRating;
    'payroll-periods': PayrollPeriod;
    payslips: Payslip;
    messages: Message;
    'message-recipients': MessageRecipient;
    'email-templates': EmailTemplate;
    notifications: Notification;
    holidays: Holiday;
    users: User;
    media: Media;
    'audit-logs': AuditLog;
    'import-jobs': ImportJob;
    'login-challenges': LoginChallenge;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    employees: EmployeesSelect<false> | EmployeesSelect<true>;
    branches: BranchesSelect<false> | BranchesSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    'wellness-leaves': WellnessLeavesSelect<false> | WellnessLeavesSelect<true>;
    'itr-submissions': ItrSubmissionsSelect<false> | ItrSubmissionsSelect<true>;
    'sworn-declarations': SwornDeclarationsSelect<false> | SwornDeclarationsSelect<true>;
    'pds-submissions': PdsSubmissionsSelect<false> | PdsSubmissionsSelect<true>;
    'ipcr-ratings': IpcrRatingsSelect<false> | IpcrRatingsSelect<true>;
    'payroll-periods': PayrollPeriodsSelect<false> | PayrollPeriodsSelect<true>;
    payslips: PayslipsSelect<false> | PayslipsSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    'message-recipients': MessageRecipientsSelect<false> | MessageRecipientsSelect<true>;
    'email-templates': EmailTemplatesSelect<false> | EmailTemplatesSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    holidays: HolidaysSelect<false> | HolidaysSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'import-jobs': ImportJobsSelect<false> | ImportJobsSelect<true>;
    'login-challenges': LoginChallengesSelect<false> | LoginChallengesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'leave-settings': LeaveSetting;
    'notification-settings': NotificationSetting;
    'payslip-settings': PayslipSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'leave-settings': LeaveSettingsSelect<false> | LeaveSettingsSelect<true>;
    'notification-settings': NotificationSettingsSelect<false> | NotificationSettingsSelect<true>;
    'payslip-settings': PayslipSettingsSelect<false> | PayslipSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employees".
 */
export interface Employee {
  id: number;
  fullName?: string | null;
  profilePicture?: (number | null) | Media;
  lastName: string;
  firstName: string;
  middleName?: string | null;
  extension?: string | null;
  gender: 'Male' | 'Female';
  dateOfBirth?: string | null;
  /**
   * Computed from date of birth
   */
  age?: number | null;
  civilStatus?: ('Single' | 'Married' | 'Widowed' | 'Separated' | 'Annulled' | 'Solo Parent') | null;
  religion?: string | null;
  bloodType?: ('A+' | 'A-' | 'B+' | 'B-' | 'AB+' | 'AB-' | 'O+' | 'O-') | null;
  professionalEligibility?: string | null;
  contactNumber?: string | null;
  email?: string | null;
  address?: string | null;
  educationalAttainment?:
    | (
        | 'Elementary Undergraduate'
        | 'Elementary Graduate'
        | 'High School Undergraduate'
        | 'High School Graduate'
        | 'Senior High School Graduate'
        | 'Vocational / Technical'
        | 'College Undergraduate'
        | 'College Graduate'
        | "Master's Units"
        | "Master's Degree"
        | 'Doctoral Units'
        | 'Doctoral Degree'
      )
    | null;
  courses?: string | null;
  yearLevelEarnedUnits?: string | null;
  academicHonors?: string | null;
  employeeId: string;
  classification: 'COS' | 'Contractual' | 'Regular';
  employmentStatus: 'Active' | 'Resigned' | 'Retired' | 'Terminated';
  station?: (number | null) | Branch;
  region?:
    | (
        | 'NCR'
        | 'CAR'
        | 'Region I'
        | 'Region II'
        | 'Region III'
        | 'Region IV-A'
        | 'MIMAROPA'
        | 'Region V'
        | 'Region VI'
        | 'NIR'
        | 'Region VII'
        | 'Region VIII'
        | 'Region IX'
        | 'Region X'
        | 'Region XI'
        | 'Region XII'
        | 'Region XIII'
        | 'BARMM'
      )
    | null;
  position?: string | null;
  natureOfWork?: string | null;
  driverLicenseNumber?: string | null;
  dateHired?: string | null;
  lastDayOfService?: string | null;
  lengthOfService?: string | null;
  remarks?: string | null;
  sss?: string | null;
  pagibig?: string | null;
  tin?: string | null;
  philhealth?: string | null;
  emergencyContactName?: string | null;
  emergencyRelationship?: string | null;
  emergencyContactNumber?: string | null;
  emergencyAddress?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  isPublic?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branches".
 */
export interface Branch {
  id: number;
  name: string;
  /**
   * Optional short code used in Excel imports.
   */
  code?: string | null;
  address?: string | null;
  region?:
    | (
        | 'NCR'
        | 'CAR'
        | 'Region I'
        | 'Region II'
        | 'Region III'
        | 'Region IV-A'
        | 'MIMAROPA'
        | 'Region V'
        | 'Region VI'
        | 'NIR'
        | 'Region VII'
        | 'Region VIII'
        | 'Region IX'
        | 'Region X'
        | 'Region XI'
        | 'Region XII'
        | 'Region XIII'
        | 'BARMM'
      )
    | null;
  contactNumber?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: number;
  applicationId: string;
  applicantName: string;
  positionApplied: string;
  station?: (number | null) | Branch;
  /**
   * Name of the employee being replaced, if any.
   */
  replacement?: string | null;
  dateApplied: string;
  startOjt?: string | null;
  applicationStatus: 'Pending' | 'For Interview' | 'For OJT' | 'Hired' | 'Not Hired' | 'Withdrawn';
  reqPds: 'Pending' | 'Submitted' | 'Verified' | 'N/A';
  reqSpecimenSign: 'Pending' | 'Submitted' | 'Verified' | 'N/A';
  reqSwornDeclaration: 'Pending' | 'Submitted' | 'Verified' | 'N/A';
  reqTinVerification: 'Pending' | 'Submitted' | 'Verified' | 'N/A';
  reqPoliceClearance: 'Pending' | 'Submitted' | 'Verified' | 'N/A';
  reqMedicalLab: 'Pending' | 'Submitted' | 'Verified' | 'N/A';
  reqLandbankAccount: 'Pending' | 'Submitted' | 'Verified' | 'N/A';
  reqAssumptionOfDuty: 'Pending' | 'Submitted' | 'Verified' | 'N/A';
  reqDriverLicense: 'Pending' | 'Submitted' | 'Verified' | 'N/A';
  reqOrCr: 'Pending' | 'Submitted' | 'Verified' | 'N/A';
  dateSubmitted?: string | null;
  /**
   * Computed: Complete when every requirement is Submitted, Verified or N/A.
   */
  requirementsStatus?: ('Complete' | 'Incomplete') | null;
  requirementsMissing?: number | null;
  remarks?: string | null;
  /**
   * Linked automatically when the applicant is converted to an employee.
   */
  employee?: (number | null) | Employee;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wellness-leaves".
 */
export interface WellnessLeaf {
  id: number;
  employee: number | Employee;
  lastName?: string | null;
  firstName?: string | null;
  middleName?: string | null;
  dateFiling: string;
  inclusiveDateFrom: string;
  inclusiveDateTo: string;
  dateReceived?: string | null;
  /**
   * Disapproved and cancelled filings do not use up leave days.
   */
  status: 'Approved' | 'Pending' | 'Disapproved' | 'Cancelled';
  days?: number | null;
  year?: number | null;
  daysByYear?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  remarks?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "itr-submissions".
 */
export interface ItrSubmission {
  id: number;
  employee: number | Employee;
  year: number;
  lastName?: string | null;
  firstName?: string | null;
  middleName?: string | null;
  extension?: string | null;
  dateSubmitted?: string | null;
  dateReceived?: string | null;
  remarks?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sworn-declarations".
 */
export interface SwornDeclaration {
  id: number;
  employee: number | Employee;
  year: number;
  lastName?: string | null;
  firstName?: string | null;
  middleName?: string | null;
  station?: string | null;
  jobTitle?: string | null;
  tin?: string | null;
  dateSubmitted?: string | null;
  dateReceived?: string | null;
  remarks?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pds-submissions".
 */
export interface PdsSubmission {
  id: number;
  employee: number | Employee;
  year: number;
  lastName?: string | null;
  firstName?: string | null;
  middleName?: string | null;
  station?: string | null;
  jobTitle?: string | null;
  dateSubmitted?: string | null;
  dateReceived?: string | null;
  remarks?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ipcr-ratings".
 */
export interface IpcrRating {
  id: number;
  employee: number | Employee;
  year: number;
  lastName?: string | null;
  firstName?: string | null;
  middleName?: string | null;
  station?: string | null;
  jobTitle?: string | null;
  ratingPeriod: 'Jan-Jun' | 'Jul-Dec';
  periodFrom?: string | null;
  periodTo?: string | null;
  /**
   * 1.000 – 5.000
   */
  rating?: number | null;
  adjectivalRating?: string | null;
  dateSubmitted?: string | null;
  dateReceived?: string | null;
  remarks?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payroll-periods".
 */
export interface PayrollPeriod {
  id: number;
  /**
   * e.g. "October 2026 — 1st half"
   */
  name: string;
  /**
   * Short unique code, e.g. 2026-10-A
   */
  code: string;
  periodStart: string;
  periodEnd: string;
  payDate: string;
  /**
   * Released periods have been emailed to employees.
   */
  status: 'Draft' | 'Released';
  releasedAt?: string | null;
  releasedBy?: (number | null) | User;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'system-admin' | 'hr-staff';
  /**
   * Only approved accounts can sign in.
   */
  status: 'pending' | 'approved' | 'disabled';
  /**
   * Set when the user enters an emailed code.
   */
  emailVerified?: boolean | null;
  approvedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payslips".
 */
export interface Payslip {
  id: number;
  period: number | PayrollPeriod;
  employee: number | Employee;
  fullName?: string | null;
  employeeCode?: string | null;
  position?: string | null;
  station?: string | null;
  classification?: string | null;
  tin?: string | null;
  sss?: string | null;
  philhealth?: string | null;
  pagibig?: string | null;
  earnings?:
    | {
        label: string;
        amount: number;
        id?: string | null;
      }[]
    | null;
  deductions?:
    | {
        label: string;
        amount: number;
        id?: string | null;
      }[]
    | null;
  grossPay?: number | null;
  totalDeductions?: number | null;
  netPay?: number | null;
  remarks?: string | null;
  /**
   * Changed after the payroll was released — consider re-sending it.
   */
  correctedAfterRelease?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: number;
  subject: string;
  body: string;
  category?: ('Leave' | 'Payroll' | 'Announcement' | 'Reminder' | 'General' | 'System') | null;
  /**
   * Who it was sent to, in words.
   */
  audience?: string | null;
  attachments?: (number | Media)[] | null;
  automatic?: boolean | null;
  relatedCollection?: string | null;
  relatedId?: string | null;
  sentBy?: (number | null) | User;
  sentByName?: string | null;
  status: 'queued' | 'sending' | 'sent' | 'partial' | 'failed';
  total?: number | null;
  sent?: number | null;
  failed?: number | null;
  skipped?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "message-recipients".
 */
export interface MessageRecipient {
  id: number;
  message: number | Message;
  name?: string | null;
  email?: string | null;
  employee?: (number | null) | Employee;
  user?: (number | null) | User;
  subject?: string | null;
  body?: string | null;
  /**
   * Attach this payslip as a PDF.
   */
  payslip?: (number | null) | Payslip;
  status: 'queued' | 'sending' | 'sent' | 'failed' | 'skipped';
  attempts?: number | null;
  nextAttemptAt?: string | null;
  error?: string | null;
  sentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-templates".
 */
export interface EmailTemplate {
  id: number;
  name: string;
  /**
   * Set for templates used by automatic emails (they cannot be deleted).
   */
  key?: string | null;
  category: 'Leave' | 'Payroll' | 'Announcement' | 'Reminder' | 'General' | 'System';
  subject: string;
  body: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  user: number | User;
  title: string;
  body?: string | null;
  link?: string | null;
  readAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "holidays".
 */
export interface Holiday {
  id: number;
  date: string;
  name: string;
  type?: ('Regular Holiday' | 'Special Non-Working Day' | 'Local Holiday' | 'Office Closure') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  user?: (number | null) | User;
  userName?: string | null;
  action: string;
  collectionSlug: string;
  docId?: string | null;
  docLabel?: string | null;
  changes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-jobs".
 */
export interface ImportJob {
  id: number;
  fileName: string;
  module: string;
  status: 'committed' | 'failed';
  created?: number | null;
  updated?: number | null;
  unchanged?: number | null;
  error?: string | null;
  user?: (number | null) | User;
  userName?: string | null;
  /**
   * Copy of the imported workbook in DATA_DIR/imports.
   */
  archiveFile?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "login-challenges".
 */
export interface LoginChallenge {
  id: number;
  key: string;
  purpose: 'login' | 'register';
  user: number | User;
  codeHash: string;
  tokenEnc?: string | null;
  tokenExp?: number | null;
  expiresAt: string;
  attempts?: number | null;
  sendCount?: number | null;
  lastSentAt?: string | null;
  ip?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'employees';
        value: number | Employee;
      } | null)
    | ({
        relationTo: 'branches';
        value: number | Branch;
      } | null)
    | ({
        relationTo: 'applications';
        value: number | Application;
      } | null)
    | ({
        relationTo: 'wellness-leaves';
        value: number | WellnessLeaf;
      } | null)
    | ({
        relationTo: 'itr-submissions';
        value: number | ItrSubmission;
      } | null)
    | ({
        relationTo: 'sworn-declarations';
        value: number | SwornDeclaration;
      } | null)
    | ({
        relationTo: 'pds-submissions';
        value: number | PdsSubmission;
      } | null)
    | ({
        relationTo: 'ipcr-ratings';
        value: number | IpcrRating;
      } | null)
    | ({
        relationTo: 'payroll-periods';
        value: number | PayrollPeriod;
      } | null)
    | ({
        relationTo: 'payslips';
        value: number | Payslip;
      } | null)
    | ({
        relationTo: 'messages';
        value: number | Message;
      } | null)
    | ({
        relationTo: 'message-recipients';
        value: number | MessageRecipient;
      } | null)
    | ({
        relationTo: 'email-templates';
        value: number | EmailTemplate;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'holidays';
        value: number | Holiday;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'import-jobs';
        value: number | ImportJob;
      } | null)
    | ({
        relationTo: 'login-challenges';
        value: number | LoginChallenge;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employees_select".
 */
export interface EmployeesSelect<T extends boolean = true> {
  fullName?: T;
  profilePicture?: T;
  lastName?: T;
  firstName?: T;
  middleName?: T;
  extension?: T;
  gender?: T;
  dateOfBirth?: T;
  age?: T;
  civilStatus?: T;
  religion?: T;
  bloodType?: T;
  professionalEligibility?: T;
  contactNumber?: T;
  email?: T;
  address?: T;
  educationalAttainment?: T;
  courses?: T;
  yearLevelEarnedUnits?: T;
  academicHonors?: T;
  employeeId?: T;
  classification?: T;
  employmentStatus?: T;
  station?: T;
  region?: T;
  position?: T;
  natureOfWork?: T;
  driverLicenseNumber?: T;
  dateHired?: T;
  lastDayOfService?: T;
  lengthOfService?: T;
  remarks?: T;
  sss?: T;
  pagibig?: T;
  tin?: T;
  philhealth?: T;
  emergencyContactName?: T;
  emergencyRelationship?: T;
  emergencyContactNumber?: T;
  emergencyAddress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branches_select".
 */
export interface BranchesSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  address?: T;
  region?: T;
  contactNumber?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  applicationId?: T;
  applicantName?: T;
  positionApplied?: T;
  station?: T;
  replacement?: T;
  dateApplied?: T;
  startOjt?: T;
  applicationStatus?: T;
  reqPds?: T;
  reqSpecimenSign?: T;
  reqSwornDeclaration?: T;
  reqTinVerification?: T;
  reqPoliceClearance?: T;
  reqMedicalLab?: T;
  reqLandbankAccount?: T;
  reqAssumptionOfDuty?: T;
  reqDriverLicense?: T;
  reqOrCr?: T;
  dateSubmitted?: T;
  requirementsStatus?: T;
  requirementsMissing?: T;
  remarks?: T;
  employee?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wellness-leaves_select".
 */
export interface WellnessLeavesSelect<T extends boolean = true> {
  employee?: T;
  lastName?: T;
  firstName?: T;
  middleName?: T;
  dateFiling?: T;
  inclusiveDateFrom?: T;
  inclusiveDateTo?: T;
  dateReceived?: T;
  status?: T;
  days?: T;
  year?: T;
  daysByYear?: T;
  remarks?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "itr-submissions_select".
 */
export interface ItrSubmissionsSelect<T extends boolean = true> {
  employee?: T;
  year?: T;
  lastName?: T;
  firstName?: T;
  middleName?: T;
  extension?: T;
  dateSubmitted?: T;
  dateReceived?: T;
  remarks?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sworn-declarations_select".
 */
export interface SwornDeclarationsSelect<T extends boolean = true> {
  employee?: T;
  year?: T;
  lastName?: T;
  firstName?: T;
  middleName?: T;
  station?: T;
  jobTitle?: T;
  tin?: T;
  dateSubmitted?: T;
  dateReceived?: T;
  remarks?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pds-submissions_select".
 */
export interface PdsSubmissionsSelect<T extends boolean = true> {
  employee?: T;
  year?: T;
  lastName?: T;
  firstName?: T;
  middleName?: T;
  station?: T;
  jobTitle?: T;
  dateSubmitted?: T;
  dateReceived?: T;
  remarks?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ipcr-ratings_select".
 */
export interface IpcrRatingsSelect<T extends boolean = true> {
  employee?: T;
  year?: T;
  lastName?: T;
  firstName?: T;
  middleName?: T;
  station?: T;
  jobTitle?: T;
  ratingPeriod?: T;
  periodFrom?: T;
  periodTo?: T;
  rating?: T;
  adjectivalRating?: T;
  dateSubmitted?: T;
  dateReceived?: T;
  remarks?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payroll-periods_select".
 */
export interface PayrollPeriodsSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  periodStart?: T;
  periodEnd?: T;
  payDate?: T;
  status?: T;
  releasedAt?: T;
  releasedBy?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payslips_select".
 */
export interface PayslipsSelect<T extends boolean = true> {
  period?: T;
  employee?: T;
  fullName?: T;
  employeeCode?: T;
  position?: T;
  station?: T;
  classification?: T;
  tin?: T;
  sss?: T;
  philhealth?: T;
  pagibig?: T;
  earnings?:
    | T
    | {
        label?: T;
        amount?: T;
        id?: T;
      };
  deductions?:
    | T
    | {
        label?: T;
        amount?: T;
        id?: T;
      };
  grossPay?: T;
  totalDeductions?: T;
  netPay?: T;
  remarks?: T;
  correctedAfterRelease?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  subject?: T;
  body?: T;
  category?: T;
  audience?: T;
  attachments?: T;
  automatic?: T;
  relatedCollection?: T;
  relatedId?: T;
  sentBy?: T;
  sentByName?: T;
  status?: T;
  total?: T;
  sent?: T;
  failed?: T;
  skipped?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "message-recipients_select".
 */
export interface MessageRecipientsSelect<T extends boolean = true> {
  message?: T;
  name?: T;
  email?: T;
  employee?: T;
  user?: T;
  subject?: T;
  body?: T;
  payslip?: T;
  status?: T;
  attempts?: T;
  nextAttemptAt?: T;
  error?: T;
  sentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-templates_select".
 */
export interface EmailTemplatesSelect<T extends boolean = true> {
  name?: T;
  key?: T;
  category?: T;
  subject?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  user?: T;
  title?: T;
  body?: T;
  link?: T;
  readAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "holidays_select".
 */
export interface HolidaysSelect<T extends boolean = true> {
  date?: T;
  name?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  status?: T;
  emailVerified?: T;
  approvedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  isPublic?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  user?: T;
  userName?: T;
  action?: T;
  collectionSlug?: T;
  docId?: T;
  docLabel?: T;
  changes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-jobs_select".
 */
export interface ImportJobsSelect<T extends boolean = true> {
  fileName?: T;
  module?: T;
  status?: T;
  created?: T;
  updated?: T;
  unchanged?: T;
  error?: T;
  user?: T;
  userName?: T;
  archiveFile?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "login-challenges_select".
 */
export interface LoginChallengesSelect<T extends boolean = true> {
  key?: T;
  purpose?: T;
  user?: T;
  codeHash?: T;
  tokenEnc?: T;
  tokenExp?: T;
  expiresAt?: T;
  attempts?: T;
  sendCount?: T;
  lastSentAt?: T;
  ip?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  companyName: string;
  tagline?: string | null;
  /**
   * PNG, SVG or JPG. Marked public automatically so it shows on the login page.
   */
  logo?: (number | null) | Media;
  palette: {
    /**
     * Hex color, e.g. #1d4ed8
     */
    primary: string;
    /**
     * Hex color, e.g. #1d4ed8
     */
    secondary: string;
    /**
     * Hex color, e.g. #1d4ed8
     */
    accent: string;
    /**
     * Hex color, e.g. #1d4ed8
     */
    success: string;
    /**
     * Hex color, e.g. #1d4ed8
     */
    warning: string;
    /**
     * Hex color, e.g. #1d4ed8
     */
    danger: string;
  };
  /**
   * Used until a user picks light or dark mode themselves.
   */
  defaultTheme: 'light' | 'dark' | 'system';
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leave-settings".
 */
export interface LeaveSetting {
  id: number;
  /**
   * Applies to every year that has no specific override below.
   */
  annualAllowance: number;
  /**
   * Set a different allowance for a specific year. Past years keep their own value when the default changes.
   */
  yearOverrides?:
    | {
        year: number;
        allowance: number;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-settings".
 */
export interface NotificationSetting {
  id: number;
  leaveFiledToEmployee?: boolean | null;
  leaveStatusToEmployee?: boolean | null;
  payrollReleasedToEmployee?: boolean | null;
  registrationToAdmins?: boolean | null;
  /**
   * Shared hosting mail servers usually allow 100–500 per hour. Extra emails wait in the queue.
   */
  hourlyLimit: number;
  /**
   * Where replies go (e.g. the HR office mailbox). Leave blank to use the sender address.
   */
  replyTo?: string | null;
  footer?: string | null;
  /**
   * Secret used by the cron job that sends queued emails (/internal/queue?key=…).
   */
  queueKey?: string | null;
  smtpLastError?: string | null;
  smtpLastErrorAt?: string | null;
  smtpLastOkAt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payslip-settings".
 */
export interface PayslipSetting {
  id: number;
  title: string;
  /**
   * Leave blank to use the name from Branding.
   */
  companyName?: string | null;
  /**
   * One line per row, e.g. address, TIN, contact number.
   */
  addressLines?: string | null;
  showLogo?: boolean | null;
  currencySymbol?: string | null;
  /**
   * These become the columns of the payroll grid, Excel sheet and payslip. Order matters.
   */
  earningItems?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * These become the columns of the payroll grid, Excel sheet and payslip. Order matters.
   */
  deductionItems?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  show?: {
    employeeId?: boolean | null;
    position?: boolean | null;
    station?: boolean | null;
    classification?: boolean | null;
    tin?: boolean | null;
    sss?: boolean | null;
    philhealth?: boolean | null;
    pagibig?: boolean | null;
  };
  preparedByName?: string | null;
  preparedByTitle?: string | null;
  certifiedByName?: string | null;
  certifiedByTitle?: string | null;
  footerNote?: string | null;
  paperSize: 'A4' | 'Letter' | 'Half-Letter';
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  tagline?: T;
  logo?: T;
  palette?:
    | T
    | {
        primary?: T;
        secondary?: T;
        accent?: T;
        success?: T;
        warning?: T;
        danger?: T;
      };
  defaultTheme?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leave-settings_select".
 */
export interface LeaveSettingsSelect<T extends boolean = true> {
  annualAllowance?: T;
  yearOverrides?:
    | T
    | {
        year?: T;
        allowance?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-settings_select".
 */
export interface NotificationSettingsSelect<T extends boolean = true> {
  leaveFiledToEmployee?: T;
  leaveStatusToEmployee?: T;
  payrollReleasedToEmployee?: T;
  registrationToAdmins?: T;
  hourlyLimit?: T;
  replyTo?: T;
  footer?: T;
  queueKey?: T;
  smtpLastError?: T;
  smtpLastErrorAt?: T;
  smtpLastOkAt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payslip-settings_select".
 */
export interface PayslipSettingsSelect<T extends boolean = true> {
  title?: T;
  companyName?: T;
  addressLines?: T;
  showLogo?: T;
  currencySymbol?: T;
  earningItems?:
    | T
    | {
        label?: T;
        id?: T;
      };
  deductionItems?:
    | T
    | {
        label?: T;
        id?: T;
      };
  show?:
    | T
    | {
        employeeId?: T;
        position?: T;
        station?: T;
        classification?: T;
        tin?: T;
        sss?: T;
        philhealth?: T;
        pagibig?: T;
      };
  preparedByName?: T;
  preparedByTitle?: T;
  certifiedByName?: T;
  certifiedByTitle?: T;
  footerNote?: T;
  paperSize?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}